### PR TITLE
TestConfiguration implementation example 

### PR DESCRIPTION
**Pull request by cbenaveen**
TestConfiguration implementation example that is accompanies the Test Configuration blog post

Please review the changes you did in this PR and check these points to make sure that the code examples are of high quality:

- [x] the source branch for this PR is NOT the master branch of your fork (please create a dedicated branch for the PR)
- [x] the PR doesn't contain code that is irrelevant to the topic of the article
- [x] the PR doesn't contain any other files that are irrelevant to the topic of the article
- [ ] the PR contains a README.md file that explains in a sentence or two what the code example is about and links to the article on reflectoring.io (if you added to an existing module, please add the link to the existing README.md file)
- [ ] the code is covered with tests where it makes sense
- [ ] if you have created a new Maven or Gradle module, please add it to the CI build (search for "# ADD NEW MODULES HERE" in `build-all.sh`)
- [ ] used the latest Gradle or Maven version
- [x] used Java 11 or later 
- [ ] the [GitHub Actions build](https://github.com/thombergs/code-examples/actions?query=workflow%3ACI) is successful for your PR branch

**Feel free to raise the PR even if the checklist hasn't been worked through, yet**. But please only flag it to be reviewed after going through the checklist above.

Also feel free to reach out if you have any trouble with any of the steps.

### CODE REVIEW

**Review by pratikdas — APPROVED** [review]

**Review by pratikdas — CHANGES_REQUESTED** [review]
Please add your project to build-all.sh.

**Comment by pratikdas** [comment]
Change Sysout to log.info
Do you need the actuator in pom.xml? if not remove it.

**Comment by cbenaveen** [comment]
> Please add your project to build-all.sh.

Added the project under module5. Here is the commit: https://github.com/thombergs/code-examples/pull/85/files#diff-53a2ed270ba970fff63d42afd532bf4262ba4d69530d06bb7e40b273fe6e2b59R89

**Comment by cbenaveen** [comment]
> Do you need the actuator in pom.xml? if not remove it.

No; its not required. removed the actuator

**Comment by cbenaveen** [comment]
> Change Sysout to log.info

Removed all Sysout's instead using SLF4J logger

**Pull request merged**
